version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD="/run/secrets/sql_password"
    secrets:
      - sql_password
    ports:
      - "1433:1433"
secrets:
  sql_password:
  file: ./secrets/sql_password.txt